const hotel= [
    "Sunset Inn",
    "Oceanview Hotel",
    "Mountain Lodge",
    "Riverfront Motel",
    "City Center Hostel",
    "Blue Sky Hotel",
    "Golden Sands Resort",
    "Green Valley Inn",
    "Harbor Lights Motel",
    "Lakeview Hostel",
    "Sunnyvale Hotel",
    "Desert Oasis Inn",
    "Forest Retreat Lodge",
    "Downtown Motel",
    "Country Roads Hostel",
    "Seaside Hotel",
    "Snowy Peaks Inn",
    "Riverside Motel",
    "Urban Haven Hostel",
    "Cedar Grove Hotel",
    "Coastal Breeze Inn",
    "Highland Lodge",
    "Parkside Motel",
    "Old Town Hostel",
    "Whispering Pines Hotel",
    "Canyon View Inn",
    "Majestic Mountains Motel",
    "Harbor Side Hostel",
    "Golden Gate Hotel",
    "Prairie Inn",
    "Crystal Springs Motel",
    "Beachfront Hostel",
    "Tranquil Waters Hotel",
    "Grand View Inn",
    "Pine Forest Motel",
    "Red Rock Hostel",
    "Eagle's Nest Hotel",
    "Shoreline Inn",
    "Maple Leaf Motel",
    "Bright Star Hostel",
    "Coral Reef Hotel",
    "Hidden Valley Inn",
    "Skyline Motel",
    "Historic District Hostel",
    "Sandy Shores Hotel",
    "Mystic River Inn",
    "Treetop Motel",
    "Pioneer Hostel",
    "Lakeside Hotel",
    "Blue Lagoon Inn",
    "Wildflower Motel",
    "Timberline Hostel",
    "Harbor Hill Hotel",
    "Silver Springs Inn",
    "Bayside Motel",
    "Cobblestone Hostel",
    "Golden Palm Hotel",
    "Mountain View Inn",
    "Riverbend Motel",
    "Sunrise Hostel",
    "Prairie Rose Hotel",
    "Cedar Lodge Motel",
    "Seabreeze Hostel",
    "Wintergreen Hotel",
    "Desert Winds Inn",
    "Old Mill Motel",
    "Sunflower Hostel",
    "Marina Bay Hotel",
    "Hilltop Inn",
    "Canyon Crest Motel",
    "Pine Ridge Hostel",
    "Bayview Hotel",
    "Sierra Vista Inn",
    "Copper Mountain Motel",
    "Urban Oasis Hostel",
    "Cherry Blossom Hotel",
    "Rustic Trail Inn",
    "Seaside Heights Motel",
    "Golden Fields Hostel",
    "Royal Palm Hotel",
    "Redwood Inn",
    "Sunset Beach Motel",
    "Misty Mountain Hostel",
    "Ocean Breeze Hotel",
    "Maplewood Inn",
    "Silver Birch Motel",
    "Golden Sunrise Hostel",
    "Lakewood Hotel",
    "Sunset Valley Inn",
    "Riverstone Motel",
    "Pine Cone Hostel",
    "Harborview Hotel",
    "Sapphire Springs Inn",
    "Highway Lodge Motel",
    "Seaside Escape Hostel",
    "Forest Glade Hotel",
    "Mystic Pines Inn",
    "Waterfront Motel",
    "Grand Harbor Hostel"
];
const restaurants = [
    "The Gourmet Kitchen",
    "La Bella Italia",
    "Sushi Sakura",
    "Taco Fiesta",
    "The Curry House",
    "Le Petit Bistro",
    "Dragon Palace",
    "Steakhouse Prime",
    "Bella Pasta",
    "The French Quarter",
    "The Seafood Shack",
    "Spice Route",
    "El Mariachi",
    "The Italian Oven",
    "Noodle Nook",
    "Taste of India",
    "The Sushi Bar",
    "The Greek Taverna",
    "Casa de Tapas",
    "The Burger Joint",
    "BBQ Pit",
    "Mamma Mia Pizzeria",
    "Golden Dragon",
    "The Steak Loft",
    "Pasta Primavera",
    "French Brasserie",
    "The Fish Market",
    "Spice Junction",
    "Cantina Mexicana",
    "Italian Trattoria",
    "Noodle House",
    "Royal India",
    "Sakura Sushi",
    "Mediterranean Grill",
    "Tapas Bar",
    "The Burger House",
    "Smokey's BBQ",
    "Pizza Napoli",
    "Imperial Garden",
    "Steak and Ale",
    "Pasta Palace",
    "Bistro de Paris",
    "The Oyster Bar",
    "Spice Bazaar",
    "El Sombrero",
    "Trattoria Roma",
    "Ramen Ramen",
    "Maharaja Palace",
    "Sushi Zen",
    "Greek Islands",
    "Tapas Lounge",
    "Burger Haven",
    "BBQ Shack",
    "Pizza Bella",
    "Dragon's Den",
    "Steak Ranch",
    "Pasta Delight",
    "Le Cafe Parisien",
    "Fish & Chips",
    "Spice Market",
    "Casa Mexicana",
    "The Italian Place",
    "Noodle Delight",
    "Taste of Thailand",
    "Sushi World",
    "Mediterranean Bistro",
    "Tapas Terrace",
    "Burger Barn",
    "Smokey Joe's BBQ",
    "Pizza Pronto",
    "Golden Pavilion",
    "Steakhouse Supreme",
    "Pasta Fresca",
    "Cafe de la Mer",
    "The Crab Shack",
    "Spice Emporium",
    "El Camino",
    "Trattoria Toscana",
    "Noodle Express",
    "Indian Spice",
    "Sakura Garden",
    "Greek Tavern",
    "Tapas Street",
    "The Burger Spot",
    "BBQ Ribs",
    "Pizza Milano",
    "Mandarin Palace",
    "Steak & Grill",
    "Pasta Amore",
    "Le Gourmet Bistro",
    "The Lobster Pot",
    "Spice Pavilion",
    "Casa del Sol",
    "Ristorante Italia",
    "Noodle Garden",
    "Taste of Japan",
    "Sushi Haven",
    "Mediterranean Delight",
    "Tapas Bar & Grill"
];



var londonp= [
  "Buckingham Palace",
  "Tower of London",
  "Tower Bridge",
  "London Eye",
  "Hyde Park",
  "The British Museum",
  "National Gallery",
  "St Paul's Cathedral",
  "Churchill War Rooms",
  "Kensington Palace",
  "Camden Market",
  "Borough Market",
  "Victoria and Albert Museum",
  "Natural History Museum",
  "Westminster Abbey",
  "Shakespeare's Globe",
  "Tate Modern",
  "Kew Gardens",
  "Warner Bros Studio Tour London - The Making of Harry Potter"
];
var parisp= [
  "Eiffel Tower",
  "Louvre Museum",
  "Notre Dame Cathedral",
  "Arc de Triomphe",
  "Montmartre",
  "Palace of Versailles",
  "Musée d'Orsay",
  "Champs-Élysées",
  "Latin Quarter",
  "Sacré-Coeur Basilica",
  "Disneyland Paris",
  "Musée Picasso",
  "Jardin du Luxembourg",
  "Seine River",
  "Galeries Lafayette",
  "Le Marais",
  "Musée Rodin",
  "Canal Saint-Martin",
  "Catacombs of Paris"
];
var dubaip= [
  "Burj Khalifa",
  "Dubai Fountain",
  "Palm Jumeirah",
  "Atlantis, The Palm",
  "Burj Al Arab",
  "Dubai Mall",
  "Dubai Miracle Garden",
  "Dubai Museum",
  "Madinat Jumeirah",
  "Dubai Desert Conservation Reserve",
  "Sheikh Zayed Road",
  "Dubai Gold Souk",
  "Dubai Spice Souk",
  "Dubai Frame",
  "IMG Worlds of Adventure",
  "Ski Dubai"
];
var maldivesp= [
  "Malé Atoll",
  "Sun Island",
  "Banana Reef",
  "Alimatha Island",
  "Maafushi Island",
  "HP Reef",
  "Utheemu Island",
  "National Museum",
  "The Grand Friday Mosque",
  "Whale Submarine",
  "Kanuhura Island",
  "COMO Cocoa Island",
  "Dhigurah Island",
  "Fua Mulaku Atoll"
];
var barcelonap= [
  "Sagrada Familia",
  "Park Güell",
  "Casa Battló",
  "Casa Milà",
  "La Rambla",
  "Barceloneta Beach",
  "Gothic Quarter",
  "Picasso Museum",
  "Camp Nou",
  "Montjuïc",
  "National Museum of Catalan Art",
  "Santa Maria del Mar",
  "Palau Güell",
  "Icaria Beach",
  "Tibidabo",
  "Barcelona Cathedral",
  "Arc de Triomf",
  "Liceu Opera House"
];
const popularAirlines = [
  "Qatar Airways",
  "Singapore Airlines",
  "Emirates",
  "ANA All Nippon Airways",
  "Cathay Pacific Airways",
  "Japan Airlines",
  "Turkish Airlines",
  "EVA Air",
  "Air France",
  "Swiss International Air Lines",
  "Lufthansa",
  "Delta Air Lines",
  "American Airlines",
  "United Airlines",
  "British Airways",
  "KLM Royal Dutch Airlines",
  "Qantas Airways",
  "Etihad Airways",
  "Virgin Atlantic",
  "Aer Lingus"
];