const hotel= [
    "Sunset Inn",
    "Oceanview Hotel",
    "Mountain Lodge",
    "Riverfront Motel",
    "City Center Hostel",
    "Blue Sky Hotel",
    "Golden Sands Resort",
    "Green Valley Inn",
    "Harbor Lights Motel",
    "Lakeview Hostel",
    "Sunnyvale Hotel",
    "Desert Oasis Inn",
    "Forest Retreat Lodge",
    "Downtown Motel",
    "Country Roads Hostel",
    "Seaside Hotel",
    "Snowy Peaks Inn",
    "Riverside Motel",
    "Urban Haven Hostel",
    "Cedar Grove Hotel",
    "Coastal Breeze Inn",
    "Highland Lodge",
    "Parkside Motel",
    "Old Town Hostel",
    "Whispering Pines Hotel",
    "Canyon View Inn",
    "Majestic Mountains Motel",
    "Harbor Side Hostel",
    "Golden Gate Hotel",
    "Prairie Inn",
    "Crystal Springs Motel",
    "Beachfront Hostel",
    "Tranquil Waters Hotel",
    "Grand View Inn",
    "Pine Forest Motel",
    "Red Rock Hostel",
    "Eagle's Nest Hotel",
    "Shoreline Inn",
    "Maple Leaf Motel",
    "Bright Star Hostel",
    "Coral Reef Hotel",
    "Hidden Valley Inn",
    "Skyline Motel",
    "Historic District Hostel",
    "Sandy Shores Hotel",
    "Mystic River Inn",
    "Treetop Motel",
    "Pioneer Hostel",
    "Lakeside Hotel",
    "Blue Lagoon Inn",
    "Wildflower Motel",
    "Timberline Hostel",
    "Harbor Hill Hotel",
    "Silver Springs Inn",
    "Bayside Motel",
    "Cobblestone Hostel",
    "Golden Palm Hotel",
    "Mountain View Inn",
    "Riverbend Motel",
    "Sunrise Hostel",
    "Prairie Rose Hotel",
    "Cedar Lodge Motel",
    "Seabreeze Hostel",
    "Wintergreen Hotel",
    "Desert Winds Inn",
    "Old Mill Motel",
    "Sunflower Hostel",
    "Marina Bay Hotel",
    "Hilltop Inn",
    "Canyon Crest Motel",
    "Pine Ridge Hostel",
    "Bayview Hotel",
    "Sierra Vista Inn",
    "Copper Mountain Motel",
    "Urban Oasis Hostel",
    "Cherry Blossom Hotel",
    "Rustic Trail Inn",
    "Seaside Heights Motel",
    "Golden Fields Hostel",
    "Royal Palm Hotel",
    "Redwood Inn",
    "Sunset Beach Motel",
    "Misty Mountain Hostel",
    "Ocean Breeze Hotel",
    "Maplewood Inn",
    "Silver Birch Motel",
    "Golden Sunrise Hostel",
    "Lakewood Hotel",
    "Sunset Valley Inn",
    "Riverstone Motel",
    "Pine Cone Hostel",
    "Harborview Hotel",
    "Sapphire Springs Inn",
    "Highway Lodge Motel",
    "Seaside Escape Hostel",
    "Forest Glade Hotel",
    "Mystic Pines Inn",
    "Waterfront Motel",
    "Grand Harbor Hostel"
];
const restaurants = [
    "The Gourmet Kitchen",
    "La Bella Italia",
    "Sushi Sakura",
    "Taco Fiesta",
    "The Curry House",
    "Le Petit Bistro",
    "Dragon Palace",
    "Steakhouse Prime",
    "Bella Pasta",
    "The French Quarter",
    "The Seafood Shack",
    "Spice Route",
    "El Mariachi",
    "The Italian Oven",
    "Noodle Nook",
    "Taste of India",
    "The Sushi Bar",
    "The Greek Taverna",
    "Casa de Tapas",
    "The Burger Joint",
    "BBQ Pit",
    "Mamma Mia Pizzeria",
    "Golden Dragon",
    "The Steak Loft",
    "Pasta Primavera",
    "French Brasserie",
    "The Fish Market",
    "Spice Junction",
    "Cantina Mexicana",
    "Italian Trattoria",
    "Noodle House",
    "Royal India",
    "Sakura Sushi",
    "Mediterranean Grill",
    "Tapas Bar",
    "The Burger House",
    "Smokey's BBQ",
    "Pizza Napoli",
    "Imperial Garden",
    "Steak and Ale",
    "Pasta Palace",
    "Bistro de Paris",
    "The Oyster Bar",
    "Spice Bazaar",
    "El Sombrero",
    "Trattoria Roma",
    "Ramen Ramen",
    "Maharaja Palace",
    "Sushi Zen",
    "Greek Islands",
    "Tapas Lounge",
    "Burger Haven",
    "BBQ Shack",
    "Pizza Bella",
    "Dragon's Den",
    "Steak Ranch",
    "Pasta Delight",
    "Le Cafe Parisien",
    "Fish & Chips",
    "Spice Market",
    "Casa Mexicana",
    "The Italian Place",
    "Noodle Delight",
    "Taste of Thailand",
    "Sushi World",
    "Mediterranean Bistro",
    "Tapas Terrace",
    "Burger Barn",
    "Smokey Joe's BBQ",
    "Pizza Pronto",
    "Golden Pavilion",
    "Steakhouse Supreme",
    "Pasta Fresca",
    "Cafe de la Mer",
    "The Crab Shack",
    "Spice Emporium",
    "El Camino",
    "Trattoria Toscana",
    "Noodle Express",
    "Indian Spice",
    "Sakura Garden",
    "Greek Tavern",
    "Tapas Street",
    "The Burger Spot",
    "BBQ Ribs",
    "Pizza Milano",
    "Mandarin Palace",
    "Steak & Grill",
    "Pasta Amore",
    "Le Gourmet Bistro",
    "The Lobster Pot",
    "Spice Pavilion",
    "Casa del Sol",
    "Ristorante Italia",
    "Noodle Garden",
    "Taste of Japan",
    "Sushi Haven",
    "Mediterranean Delight",
    "Tapas Bar & Grill"
];

var attractions =[
"Eiffel Tower",
"Louvre Museum",
"Arc De Triumphe",
"Norte Dame Cathedral",
"Palace of Versailles",
"Le Marasis"
]