const touristDestinations = ["Paris",
    "Tokyo",
    "New York",
    "London",
    "Rome",
    "Barcelona",
    "Istanbul", 
    "Singapore",
    "Bangkok",
    "Hong Kong",
    "Sydney",
    "Amsterdam",
    "Los Angeles",
    "Moscow",
    "Vienna",
    "Venice",
    "Berlin",
    "Florence",
    "Prague",
    "Rio de Janeiro",
    "Lisbon",
    "Budapest",
    "Cairo",
    "Dublin",
    "Seoul",
    "Cape Town",
    "Shanghai",
    "Madrid",
    "San Francisco",
    "Toronto",
    "Buenos Aires",
    "Melbourne",
    "Mumbai",
    "Athens",
    "Kuala Lumpur",
    "Jerusalem",
    "Warsaw",
    "Havana",
    "Mexico City",
    "San Diego",
    "Vancouver",
    "Kyoto",
    "Osaka",
    "Jakarta",
    "Lima",
    "Bogotá",
    "Ho Chi Minh City",
    "Marrakech",
    "Bangkok",
    "Las Vegas",
    "Monaco",
    "Dubai",
    "Edinburgh",
    "Brussels",
    "Munich",
    "Stockholm",
    "Helsinki",
    "Kraków",
    "Geneva",
    "Brisbane",
    "Auckland",
    "Montreal",
    "Manila",
    "Johannesburg",
    "Doha",
    "Nice",
    "Copenhagen",
    "Luxembourg",
    "Zagreb",
    "Santiago",
    "Ljubljana",
    "Lyon",
    "Porto",
    "Nairobi",
    "Valencia",
    "Marseille",
    "Antwerp",
    "Bergen",
    "Tallinn",
    "Riga",
    "Vilnius",
    "Bucharest",
    "Sofia",
    "Belgrade",
    "Sarajevo",
    "Skopje",
    "Tirana",
    "Podgorica",
    "Pristina",
    "Chisinau",
    "Tbilisi",
    "Yerevan",
    "Baku",
    "Reykjavik",
    "St. Petersburg",
    "Kiev",
    "Almaty",
    "Nur-Sultan",
    "Tashkent",
    "Bishkek",
    "Dushanbe",
    "Ulaanbaatar",
    "Lagos",
    "Abuja",
    "Addis Ababa",
    "Accra",
    "Dakar",
    "Casablanca",
    "Rabat",
    "Tunis",
    "Algiers",
    "Tripoli",
    "Amman",
    "Beirut",
    "Baghdad",
    "Tehran",
    "Karachi",
    "Lahore",
    "Islamabad",
    "Kathmandu",
    "Thimphu",
    "Colombo",
    "Male",
    "Phnom Penh",
    "Vientiane",
    "Hanoi",
    "Yangon",
    "Dhaka",
    "Kathmandu",
    "Thimphu",
    "Colombo",
    "Male",
    "Tashkent",
    "Ashgabat",
    "Samarkand",
    "Bukhara",
    "Kabul",
    "Tbilisi",
    "Yerevan",
    "Baku",
    "Nur-Sultan",
    "Almaty",
    "Bishkek",
    "Dushanbe",
    "Ulaanbaatar",
    "Manama",
    "Doha",
    "Muscat",
    "Riyadh",
    "Jeddah",
    "Kuwait City",
    "Abu Dhabi",
    "Sharjah",
    "Mecca",
    "Medina",
    "Maldives",
    "Damascus",
    "Aleppo",
    "Homs",
    "Lattakia",
    "Baghdad",
    "Basra",
    "Erbil",
    "Mosul",
    "Tehran",
    "Mashhad",
    "Isfahan",
    "Tabriz",
    "Shiraz",
    "Qom",
    "Ahvaz",
    "Bandar Abbas",
    "Zahedan",
    "Rasht",
    "Kerman",
    "Bushehr",
    "Yazd",
    "Zanjan",
    "Hamedan",
    "Kermanshah",
    "Ilam",
    "Sanandaj",
    "Khorramabad",
    "Arak",
    "Qazvin",
    "Sari",
    "Gorgan",
    "Semnan",
    "Yasuj",
    "Bojnurd",
    "Birjand",
    "Shahrud",
    "Karaj",
    "Tabas",
    "Kashan",
    "Saveh",
    "Ardabil",
    "Maku",
    "Zabol",
    "Iranshahr",
    "Chabahar",
    "Noshahr",
    "Babol",
    "Sari",
    "Bandar-e Anzali"
];
